version: '3.8'

services:
  db:
    image: postgres:14
    container_name: history_db
    restart: always
    environment:
      POSTGRES_DB: chat_history
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  history_service:
    build: ./history_service  # path to your Dockerfile
    container_name: history_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: devuser
      DB_PASS: devpass
      DB_NAME: chat_history

volumes:
  db_data:
